// packages/svelte/components/caret-right.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-right"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <path d="M45.01 32.025L20.939 7.954l-3.008 3.009 21.061 21.062-21.061 21.062 3.008 3.008 24.071-24.07z" fill-rule="nonzero"></path>
</svg>

// packages/vue/components/caret-right.vue
<script>
export default {
  name: "TiCaretRight",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-right"
    :class="{'spin': spin}" :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <path d="M45.01 32.025L20.939 7.954l-3.008 3.009 21.061 21.062-21.061 21.062 3.008 3.008 24.071-24.07z" fill-rule="nonzero"></path>
  </svg>
</template>
