// packages/svelte/components/download.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-download"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <path d="M48.089 52.095v4H16.04v-4h32.049zm-16.025-4l-16.024-16h8.098l-.049-24h15.975l.048 24h7.977l-16.025 16z"></path>
</svg>

// packages/vue/components/download.vue
<script>
export default {
  name: "TiDownload",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-download"
    :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <path d="M48.089 52.095v4H16.04v-4h32.049zm-16.025-4l-16.024-16h8.098l-.049-24h15.975l.048 24h7.977l-16.025 16z"></path>
  </svg>
</template>
