// packages/svelte/components/star.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-star"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <path d="M32.001 9.188l5.666 17.438h18.335L41.169 37.403l5.666 17.438-14.834-10.777-14.833 10.777 5.666-17.438L8 26.626h18.335l5.666-17.438z"></path>
</svg>

// packages/vue/components/star.vue
<script>
export default {
  name: "TiStar",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-star"
    :class="{'spin': spin}" :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <path d="M32.001 9.188l5.666 17.438h18.335L41.169 37.403l5.666 17.438-14.834-10.777-14.833 10.777 5.666-17.438L8 26.626h18.335l5.666-17.438z"></path>
  </svg>
</template>
