// packages/vue/components/caret-left.vue
<script>
export default {
  name: "TiCaretLeft",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-left"
    :class="{'spin': spin}" :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <path d="M18.543 32.027l24.07-24.07 3.009 3.008L24.56 32.027l21.062 21.062-3.009 3.009-24.07-24.071z" fill-rule="nonzero"></path>
  </svg>
</template>

// packages/svelte/components/caret-left.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-left"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <path d="M18.543 32.027l24.07-24.07 3.009 3.008L24.56 32.027l21.062 21.062-3.009 3.009-24.07-24.071z" fill-rule="nonzero"></path>
</svg>
