// packages/vue/components/bold.vue
<script>
export default {
  name: "TiBold",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-bold"
    :class="{'spin': spin}" :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <text x="9.879" y="56.132" font-family="&apos;Roboto-Bold&apos;,&apos;Roboto&apos;" font-weight="700" font-size="67.597">B</text>
  </svg>
</template>

// packages/svelte/output/bold.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-bold"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <text x="9.879" y="56.132" font-family="&apos;Roboto-Bold&apos;,&apos;Roboto&apos;" font-weight="700" font-size="67.597">B</text>
</svg>
