// packages/vue/components/caret-down.vue
<script>
export default {
  name: "TiCaretDown",

  props: {
    size: { type: [String, Number], default: 24 },
    spin: { type: Boolean, default: false },
    color: { type: String, default: "currentColor" },
    stroke: { type: [String, Number], default: "0" },
    strokeColor: { type: String, default: "currentColor" }
  },
}
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-down"
    :class="{'spin': spin}" :width="size" :height="size"
    viewBox="0 0 64 64" :fill="color" :stroke="strokeColor"
    :stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round">
    <path d="M32.149 45.79L8.078 21.719l3.009-3.009 21.062 21.062L53.21 18.71l3.009 3.009-24.07 24.071z" fill-rule="nonzero"></path>
  </svg>
</template>

// packages/svelte/output/caret-down.svelte
<script>
  export let size = 24;
  export let spin = false;
  export let color = "currentColor";
  export let stroke = "0";
  export let strokeColor = "currentColor";
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="toe-icon ti ti-caret-down"
  class:spin={spin} width={size} height={size}
  viewBox="0 0 64 64" fill={color} stroke={strokeColor}
  stroke-width={stroke} stroke-linecap="round" stroke-linejoin="round">
  <path d="M32.149 45.79L8.078 21.719l3.009-3.009 21.062 21.062L53.21 18.71l3.009 3.009-24.07 24.071z" fill-rule="nonzero"></path>
</svg>
